### ISSUE TITLE
HTMLBars undefined function

### ISSUE THREAD

**Issue by chrishol** [cibernox/ember-cli-accounting#7]
We just tried to use this on an HTMLBars project (using Canary Ember) and got an `undefined is not a function`.

As far as I can tell, it's because of this line: https://github.com/cibernox/ember-cli-accounting/blob/414c8add13ef8fb288be2d2c618684b07a0f66a1/app/initializers/ember-cli-accounting.js#L5

The `helper` function doesn't seem to exist for `Ember.HTMLBars`. Should it be using `registerHelper` instead?

**Comment by cibernox** [comment]
I'll take a look. I haven't used this with HTMLBars yet.

**Comment by cibernox** [comment]
I've just released version 0.1.0, that ONLY supports HTMLBars and ember >= 1.10.0.

Basically I wanted to avoid the anoying clutter of checking if the project uses HTMLBars or Handlebars. From now on, only HTMLBars is supported. 

Version 0.0.4 has the exact same functionality and works with ember 1.9 and below.

Can you check if it works for you now?

**Comment by cibernox** [comment]
npm is down. I'll try to publish it later.

**Comment by cibernox** [comment]
Published now.

**Comment by thiagoc7** [comment]
I'm having the same issue, using 0.10.0, and ember 1.10.0

**Comment by cibernox** [comment]
I'll check it after lunch, in case something has changes in HTMLBars lately.

**Comment by alexdiliberto** [comment]
@cibernox I can also confirm this issue with EmberCLI 0.1.12 and Ember 1.10.0

For me, this line is setting the var to `undefined` https://github.com/cibernox/ember-cli-accounting/blob/ce15e7e64161e88fe0d7863f5ac459b47f20c430/app/initializers/ember-cli-accounting.js#L5

I believe it's because `registerHelper` is now set to `_registerHelper`
https://github.com/emberjs/ember.js/blob/d23f484459bad8e3581b6451e9f927b5c8c96637/packages/ember-htmlbars/lib/main.js#L70

/cc @chrishol

**Comment by cibernox** [comment]
Ok, that's very helpful. I'll fix it today.

**Comment by cibernox** [comment]
I've seen that you did a PR! Much better! Thanks

**Comment by chrishol** [comment]
Thanks all!
